config/routes.rb
Rails.application.routes.draw do
  # get 'microposts/new'
  # get 'sessions/new'
  
  root 'static_pages#home'
  get '/help', 	to: 'static_pages#help'
  get '/about', to: 'static_pages#about'

  get '/login', 	  to: 'sessions#new'
  post '/login', 	  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/signup',  to: 'users#new'
  resources :users, except: :new do
    member do
      get 'following', 'followers'
    end
  end

  resources :microposts,    only:[:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :votes,         only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_many :votes, dependent: :destroy

  default_scope -> { order(created_at: :desc) }

  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length:{maximum: 140}
  validate :picture_size

  private
  	def picture_size
  		if picture.size > 2.megabytes
  			errors.add(:picture, "should be less than 2 mb")
  		end
  	end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  
	before_action :require_login, only: [:create, :destroy]
	before_action :correct_user, only: :destroy
	
  def create
  	@micropost = current_user.microposts.create(micropost_params) 
  	if @micropost.save
  		flash[:success] = "Posted!"
  		redirect_to root_url
  	else
  		@microposts = current_user.feed.paginate(page: params[:page], per_page: 10)
  		render 'static_pages/home'
  	end
  end

  def destroy
  	@micropost = Micropost.find(params[:id])
  	@micropost.destroy
  	flash[:info] = "Delete post successfully."
  	redirect_to request.referrer || root_url
  end

  private
	def micropost_params
		params.require(:micropost).permit(:content, :picture)
	end

	def correct_user
		@micropost = current_user.microposts.find_by(id: params[:id])

		if @micropost.nil?
			flash[:danger] = "You are not allowed to do that."
			redirect_to root_url
		end
	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_downvote.html.erb
<%= button_to current_user.votes.find_by(micropost: micropost), 
			method: :delete, class: 'btn btn-default btn-xs', remote: true do %>

		<i class="glyphicon glyphicon-arrow-down"></i> 
<% end %>

app/views/microposts/_form.html.erb
<%= form_for @micropost do |f| %>
		
	<%= render "shared/error_messages", object: f.object %>

	<div class="form-group">
		<%= f.label :content %>
		<%= f.text_area :content, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.file_field :picture, accept: 'image/jpeg, image/jpg, image/png', id: 'micropost_picture' %>
	</div>

	<div>
		<%= f.submit "Post", class: "btn btn-primary form-control" %>
	</div>
<% end %>

<script>
	$('#micropost_picture').bind('change', function() {
		var size_mb = this.files[0].size/1024/1024;

		if (size_mb > 2) {
			alert(' Maximum file size is 5mb. Please choose another file.');
		}
	});
</script>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
	<%= link_to gravatar_for(micropost.user, 50), micropost.user %>
	<span class="user"><%= micropost.user.name %></span>
	<span class="content">
		<%= micropost.content %>
		<%= image_tag micropost.picture.url if micropost.picture? %>	
	</span> 

	<span class="timestamp">
		<%= time_ago_in_words(micropost.created_at) %> ago

		<% if current_user?(micropost.user) %>
			<%= link_to "delete", micropost_path(micropost), 
								method: :delete, 
			 					data: { confirm: "Are you sure?" } %>
		<% end %>
	</span>

	<section class="vote">
	<%= render "microposts/vote_form", micropost: micropost %>
	</section>
</li>

app/views/microposts/_upvote.html.erb
<%= button_to current_user.votes.build, 
			params: { micropost_id: micropost.id }, 
			class: 'btn btn-warning btn-xs', remote: true do  %>
				<i class="glyphicon glyphicon-arrow-up"></i> 
<% end %>

app/views/microposts/_vote_form.html.erb
<div class="vote_form">
	<% unless current_user.voting?(micropost) %>
		<%= render 'microposts/upvote', micropost: micropost %>
	<% else %>
		<%= render 'microposts/downvote', micropost: micropost %>
	<% end %>
</div>
<span class="vote_count">
<%= pluralize(micropost.votes.count, "vote") %>
</span>