config/routes.rb
Rails.application.routes.draw do
  # get 'microposts/new'
  # get 'sessions/new'
  
  root 'static_pages#home'
  get '/help', 	to: 'static_pages#help'
  get '/about', to: 'static_pages#about'

  get '/login', 	  to: 'sessions#new'
  post '/login', 	  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  get '/signup',  to: 'users#new'
  resources :users, except: :new do
    member do
      get 'following', 'followers'
    end
  end

  resources :microposts,    only:[:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :votes,         only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
	
	<div class="container">
		<small>The Awesome Blog</small>
		<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path%></li>
					<li><%= link_to "Help", help_path %></li>
		</ul>

</footer>

app/views/layouts/_header.html.erb
<header>
	<nav class="navbar navbar-inverse">
		<div class="container">
			<%= link_to "Awesome Blog App", root_path, id: "logo" %>

			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "About", about_path%></li>
				<li><%= link_to "Help", help_path %></li>
					
				<% if logged_in? %>
					<li><%= link_to "Index", users_path %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							<%= current_user.name %><i class="caret"></i>
						</a>

						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_url(current_user) %></li>
							<li><%= link_to "Logout", logout_path, method: :delete %></li>
						</ul>
					</li>
					
				<% else %>
					<li><%= link_to "Signup", signup_path %></li>
					<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
    
    <div class="container">

      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>

      <%= yield %>
      <%#= debug session[:user_id] %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>